name: Build
on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneOSX
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          lfs: true
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: IrukaDrive-${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: IrukaDrive-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - name: Zip build
        run: |
          pushd build/${{ matrix.targetPlatform }}
          zip -r ../../IrukaDrive-{{ matrix.targetPlatform }}.zip .
          popd